### ISSUE TITLE
Missing License 

### ISSUE THREAD

**Issue by SublimePotato** [nwcell/ics.js#11]
Hi there !

I would like to use your library in one of my projects but I cant because the license is missing. 

Please consider adding a license. 

FYI 
Code published on Github without an explicit license is protected by copyright and is by default All Rights Reserved. 
http://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github

**Comment by quincogdell** [comment]
please add a license, it's EXTREMELY important.

**Comment by jacroe** [comment]
:+1:

**Comment by hryanjones** [comment]
+1

**Comment by hawkerm** [comment]
+1

**Comment by nwcell** [comment]
Done
