### ISSUE TITLE
Time doesn't show up if minutes and seconds are 0

### ISSUE THREAD

**Issue by karanveerm** [nwcell/ics.js#15]
If the time is like 12:00 pm, i.e. minutes are not provided, then the time does not show up in the ics calendar. For example:

```
var cal = ics();
cal.addEvent('Demo Event', 'This is a one hour event', 'location', '9/28/2014 12:00 pm', '9/28/2014 1:00 pm');
cal.download();
```

will be downloaded as an all day event.

I believe it will be fixed if we change:
https://github.com/nwcell/ics.js/blob/master/ics.js#L77
to:
`if (start_hours + start_minutes + start_seconds + end_hours + end_minutes + end_seconds != 0) {`
(although I did not test this thoroughly)

**Comment by lynchkevin** [comment]
It's not just that he is using .getMinutes() instead of .getSeconds his test also forgets the hours.
karanveerm is exactly right if you change the code it does work but I also have not tested it exhaustively.
Cost me as much time as this library saved me.

**Comment by olafvanzon** [comment]
I just created a pull request to fix this issue with solution suggested by @karanveerm.

@nwcell can you check? thanks

**Comment by csavio** [comment]
You should include hours in that if statement. That is why the if statement is evaluating false not the seconds.

**Comment by keiichitealab** [comment]
So it's been 2 years since last post, but following change worked for me 👍 
` // if (start_minutes + start_minutes + start_seconds + end_minutes + end_seconds != 0) {
            if (start_hours +start_minutes + start_minutes + start_seconds + end_minutes + end_seconds != 0) {
                start_time = 'T' + start_hours + start_minutes + start_seconds;
                end_time = 'T' + end_hours + end_minutes + end_seconds;
            }`

**Comment by nwcell** [comment]
Fixed
