### ISSUE TITLE
ICS won't download on mobile

### ISSUE THREAD

**Issue by swbloom** [nwcell/ics.js#16]
Guys, this is amazing. Thank you so much for creating it.

The issue I'm having is this: the ICS files won't download on mobile devices. In Android, nothing happens. In Chrome, a new window pops up but nothing happens.

Any thoughts?

I'm using your IE version of FileSaver.

S

**Comment by staminna** [comment]
Chrome in IPad also shows a blank popup when running the demo.

**Comment by xTwIzZ** [comment]
Hi Everyone,
Does anyone know if there's been a fix for this so that it "DOES" work in mobile/tablet devices? Like the rest of you... it just opens up a blank tab from my mobile device.
Best,

**Comment by royteeuwen** [comment]
Still no one? @swbloom  you found a solution?

**Comment by nurrebass1** [comment]
Have someone found a solution to this?

**Comment by nwcell** [comment]
ics doesn't work in ios.  I've revamped the demo, but I don't think it'll fix android.  Marking as wontfix

**Comment by jamesond** [comment]
@nwcell Travis, is mobile support still a no go? The simplicity of this is awesome I just wished it had mobile support. Thank you.

**Comment by NathanBillington** [comment]
I managed to get it working on IOS by changing this line:

`blob = new Blob([calendar]);`

to

`blob = new Blob([calendar], { type: 'text/calendar' });`

Haven't tested it massively, but seems to work okay.

**Comment by adamsoderstrom** [comment]
@NathanBillington In what context do you change the variable 'blob'? I've been so far only used saveAs().

**Comment by adamsoderstrom** [comment]
I found a solution for this issue in Issue #27: https://github.com/nwcell/ics.js/issues/27#issuecomment-457681458
