### ISSUE TITLE
Seconds not filled in correctly

### ISSUE THREAD

**Issue by olafvanzon** [nwcell/ics.js#21]
Minutes are used as seconds in scheduled appointment. I will create a pull request for this bug.

**Comment by asr1** [comment]
This had been resolved in #24 but was re-introduced with the addition of rrules.

**Comment by nwcell** [comment]
Don't know when I'll get to this.  If someone sends a PR, I'll review and merge.

**Comment by fatalwall** [comment]
New to git so not sure how to provide in a better manner but the issues is with the following two lines that are feeding minutes into the seconds field. 

Line 126  var end_seconds = ("00" + (end_date.getMinutes().toString())).slice(-2);
Line 133  var now_seconds = ("00" + (now_date.getMinutes().toString())).slice(-2);

Update .getMinutes() to .getSeconds()
