### ISSUE TITLE
Doesn't work at all with Safari

### ISSUE THREAD

**Issue by immarina** [nwcell/ics.js#27]
Safari opens a blank page with no content and no download happens :(
I can't seem to pinpoint where the problem is, but if you're using the location(data method, I don't think it works at all in safari.. and if you're creating an A tag with the download property, it isn't supported by safari.

**Comment by xTwIzZ** [comment]
Hi Everyone,
Does anyone know if there's been a fix for this so that it "DOES" work in mobile/tablet devices? Like the rest of you... it just opens up a blank tab from my mobile device.
Best,

**Comment by kpettinga** [comment]
Experiencing the same issue here. On Safari 9.1.

**Comment by Garavani** [comment]
Same here. No Safari support. Any workarounds?

**Comment by wideserg** [comment]
also met the issue on Safari and IE11 - appointment  was always set to current date.
The reaseon is next line
`var start_date = new Date(begin);`

IE and Safari doesn't support format "2016-12-19 09:30", it should be at lease "2016/12/19 10:30".

**Comment by nwcell** [comment]
https://github.com/nwcell/ics.js/issues/13

**Comment by nwcell** [comment]
Ics downloads don't work on iphone

**Comment by melilocacr** [comment]
@nwcell I was able to bypass the issue on Safari for iOS devices, by skipping filesaver's download function, and instead opening a link with the ics generated code, like such:

`                var openCal = function () {
                    if (isIos()) {
                        window.open("data:text/calendar;charset=utf8," + escape(cal.build()));
                    } else {
                        cal.download();
                    }
                }`

**Comment by joaovictorrx** [comment]
> @nwcell I was able to bypass the issue on Safari for iOS devices, by skipping filesaver's download function, and instead opening a link with the ics generated code, like such:
> 
> ` var openCal = function () { if (isIos()) { window.open("data:text/calendar;charset=utf8," + escape(cal.build())); } else { cal.download(); } }`

@melilocacr  I try this and it's working in safari but, on iOS Chrome doesn't work, the browser just downloads the file and not open in calendar =/, any ideas to how solve that?

**Comment by melilocacr** [comment]
@thoraesir Yeah I couldn't fix it on Chrome either :(
