### ISSUE TITLE
saveAs is not defined

### ISSUE THREAD

**Issue by matthiaslischka** [nwcell/ics.js#42]
Hi,
thx for maintaining the repo again. Really like the library.
Unfortunately I'm facing some error now when trying to `cal.download();`:
```js
Uncaught ReferenceError: saveAs is not defined
    at Object.download (ics.js:223)
```
In addition it would be nice to have the minified version updated as well.
I would fix it myself and provide an patch but I don't know when I will find time to do so. So far I wanted to point out the issue.

BR, Matthias

**Comment by nwcell** [comment]
No worries, I've just updated the minified version.  Are you importing the filesave library?

**Comment by matthiaslischka** [comment]
Thx. Works now again using the `ics.deps.min.js` file.

BR, Matthias
