### ISSUE TITLE
No License provided

### ISSUE THREAD

**Issue by SebastianApel** [nwcell/ics.js#56]
Hi Travis, Kyle

the idea is great and I would like to use it. 
But: You do not say which license you publish under, so I have to assume the most restrictive one.
And that means: I cannot use it :-(

Would you be willing to add a license?

Kind regards,
Sebastian

**Comment by ggascoigne** [comment]
I see that there's a license file now https://github.com/nwcell/ics.js/blob/master/LICENSE.  MIT.
