### ISSUE TITLE
Lacking Minute Issue

### ISSUE THREAD

**Issue by JohnMealy23** [nwcell/ics.js#8]
First off, wonderful tool you've made here, and thank you for it.  

I'm finding that when my start- and end-time are all zeros and in the PM, only dates and no times are produced in the resulting ICS file.

Example:

```
cal_single.addEvent( 'Title', 'Description and such...', '4/20/2014 6:00 pm', '4/20/2014 7:00 pm');
```

Results in...

```
DTSTART;VALUE=DATE:20140420
DTEND;VALUE=DATE:20140420
```

Whereas...

```
cal_single.addEvent( 'Title', 'Description and such...', '4/20/2014 6:01 pm', '4/20/2014 7:01 pm');
```

Results in...

```
DTSTART;VALUE=DATE:20140420T180101
DTEND;VALUE=DATE:20140420T190101
```

Hitting a deadline right now, so I'm defaulting end times to 30 minutes after the start times.  Once I'm done with this, I'll try to go in and isolate exactly where this is occurring in the code.  I'll let you know what I find.

Testing done in Chrome 34.0.1847.116 m.

**Comment by matthiaslischka** [comment]
I have the same problem - and an related strange issue:

`cal.addEvent("title", "", "", new Date(2017,0,1,14,30,0), new Date(2017,0,1,15,0,0))`
will create
```
DTSTART;VALUE=DATE:20170101T143030
```

Why 14:30:30 - where do the 30 seconds come from?

BR Matthias

(using: https://rawgithub.com/nwcell/ics.js/master/ics.deps.min.js)

**Comment by oncarkubal** [comment]
Hi ,

I am facing the same Issue.  

Any idea how to fix this.

**Comment by matthiaslischka** [comment]
Sadly this repo seems to be not maintained anymore. Last commit 2014.
You could look at it's forks - maybe someone fixed it already.
Fork it yourself and fix it ;)
Or use an other better maintained repo. :/

**Comment by nwcell** [comment]
I've applied some PRs recently.  I believe some of them fixed this issue.
